#!/bin/sh

### Checking dependencies

which -s brew || curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
which -s terraform || (brew tap hashicorp/tap && brew install hashicorp/tap/terraform)
which -s jq || brew install jq
which -s curl || brew install curl
which -s git || brew install git


[ -d "$HOME/.terraform-automation" ] && sudo rm -rf "$HOME/.terraform-automation"
sudo git clone https://github.com/antoriche/terraform-automation "$HOME/.terraform-automation"

[ -L "/usr/local/bin/terraform-automation" ] && sudo rm -f /usr/local/bin/terraform-automation
sudo ln -sn "$HOME/.terraform-automation" /usr/local/bin/terraform-automation