version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - printenv > .env
      - npm run build
artifacts:
  files:
    - '**/*'
  name: build
  base-directory: build