version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - ENV=${ENV:-"dev"}
      - printenv > .env
      - npx serverless deploy --stage "$ENV"