version: 0.2
phases:
  install:
    commands:
      - n 14
      - npm install
  build:
    commands:
      - ENV=${ENV:-"dev"}
      - echo $VARS
      - printenv | grep -E "$VARS" | grep -v "VARS=" > .env
      - cat .env
      - npx serverless deploy --stage "$ENV"