version: 0.2
phases:
  install:
    commands:
      - n 14
      - npm install
  build:
    commands:
      - ENV=${ENV:-"dev"}
      - printenv | grep "$VARS" > .env
      - npx serverless deploy --stage "$ENV"